services:
  web:
    build: .
    container_name: online_cinema
    restart: unless-stopped
    ports:
      - ${APPLICATION_PORT}:8000
    env_file:
      - .env
      - .secret.env
    volumes:
      - ./:/online_cinema
    command: bash -c "alembic upgrade head && uvicorn app.main:app --reload --host 0.0.0.0"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    container_name: cinema_db
    ports:
      - "${POSTGRES_PORT_OUTER}:5432"
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6
    # container_name: cinema_redis - only if there are no replicas
    restart: unless-stopped
    expose:
      - "${REDIS_PORT}"
    env_file:
      - .env
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    deploy:
      replicas: 3
    command: redis-server --requirepass ${REDIS_PASSWORD}
